### PR TITLE
Templates docs page

### LINKED ISSUE #160: Adding Templates Section under Components
This task needs to wait for the CLI for templates to be enabled
This task needs to wait for the `/docs` route to be enabled

The templates section under components should start with installation instructions for the templates themselves with automatic installation and manual install for adding our pre-made templates to a user's project.

We don't have any other templates other than the minimal template so this section should be structured more or less like this:

## Templates (with id #templates).

Installation instructions for templates, please include a link to Preview mode similar to Get Started instructions but it should be way shorter.

Also please make sure to reference the templates at the end of the Get Started section with a link to the heading id.

### LINKED ISSUE #196: Headings with ID should always be clickable links
I noticed that on the Templates section in Docs there are headings with IDs. If a heading has an id it should always be a clickable link.

### PR DESCRIPTION
**Pull request by ChcJohnie**
closes #160 
closes #196 

- add templates docs page 
  - placed under docs level but imho expected to move under own /templates path in the longrun 
  - although under docs path, decided for generated page with common structure hydrated with template data 
  - temporarily(?) using MDX based elements to keep consistent docs styling
- see preview buttons correctly linked, images based on current emails
- categories descriptions generated by AI, feel free to suggest edits 🙂 
- images fade as on mainpage (shadow dimensions slightly adjusted as this looks imho better)
- download button ready, but without functionality (own task expected)
  - should I add some message/alert that download is WIP given we are merging to production? @iamhectorsosa

### CODE REVIEW

**Review by iamhectorsosa — COMMENTED** [review]
Looking good from the UI side! Will take a look at the code right after lunch!

**Review by iamhectorsosa — APPROVED** [review]

**Review by iamhectorsosa — COMMENTED** [review]
It seems that we're missing the metadata for these pages

We can use the same OG image as we do in `/preview` route

**Review by ericvalcik — DISMISSED** [review]
I don't want to block so I'm approving the changes but I will try to take a look later today

**Comment by ChcJohnie** [comment]
Added metadata
Added github folder download as temporal? download solution as discussed on slack, with downside of redirect to download page (dont think worth proxying through our api, but can look at it if needed.) @iamhectorsosa

**Review by iamhectorsosa — APPROVED** [review]
Looking good! Good job!

**Review by ericvalcik — APPROVED** [review]
Good work, approved 👍

**Comment by ChcJohnie** [comment]
Stuffed in fix for headings (oversight on my part, as hashes were displayed). Not sure about keeping that feature when templates are moved out of docs scope (personally i do not like it much, but know its useful for docs)
On same principle added PagingNav I noticed is missing.
Sorry about one more review request

**Review by iamhectorsosa — APPROVED** [review]

**Pull request merged**
