### PR TITLE
Email previews with category

### LINKED ISSUE #182: Templates Part 1 Enhancing the Preview mode for sub directories
We want to create categories for the templates. So far we may have three categories:
* Events
* Marketing
* Newsletter

Therefore, I want to organize the `src/emails` directory like this:
* `src/emails/events`
* `src/emails/marketing`
* `src/emails/newsletter`

On each of these directories I will have the emails that belong to that category. The idea is to enhance preview mode to handle these sub directories.

Open for proposals but here's what I expect to see on each page

## On the route `/preview`

I want to see preview mode without any email selected, and with a text prompting the user to select a category. The file navigator should display the three categories (belonging to the actual folders found in the directory)

## ON the route `/preview/[category]`

I want to see preview mode without any email selected, and with a text prompting the user to select an email. Similar to what we have now. The file navigator should display all the emails found in that directory

Please let me know if you have any questions

### PR DESCRIPTION
**Pull request by ChcJohnie**
Closes #182 

Features:
- Email preview works with strict folder structure (one level of folders, email tsx. files inside folders) - inside src/emails
  - files/folder can be multiword but words have to be separated with `-` for correct imports and labelling
- Email side nav 
  - supports one level [folder]/[file]
  - folder level labelled as `Category`
  - improved styling - similar to docs sidenav
  - file/folder label preference (upperscale first letter, replace hyphens, removes .tsx - eg. `tips-for-trips.tsx` -> `Tips for trips`)
  - Mobile nav is auto opened when no folder/file is selected

Notes:
- during dev mode when folder/files are added/removed, imports sometimes get bit broken with caches, did not found easy solution but should not affect build
- some things could probably be abstracted more, but decided to keep things rather simple as Im not sure how and when themes gonna be integrated (and when they are things can get refactored long term)
- decided to keep nav rather simple, have some ideas (eg. some explore cards displayed when nothing seleted), but feel like `(/docs)/templates` specific route is better place for that, while its better to keep preview more simple (could be reviewed later)

### CODE REVIEW

**Comment by ChcJohnie** [comment]
Realized missing folder/file catchers should be added

**Comment by ChcJohnie** [comment]
Should be fixed with preview bounded not-found, (experimented with dynamicParams=false, but with that only root level not-found was used, while it works with manual call)
Ready for review

**Review by iamhectorsosa — COMMENTED** [review]
Great work on structuring this. It does what we need it to do.

However, I'm not sure about the UI here. I would like to keep it as closely as possible to a clear file explorer UI. We could get creative in doing so but I would also be fine with something minimal like this:

I just created this from the inspector.

image

We could add an icon to the folders if you want. Less is more in this case. Let's put together something minimal and nice.

image

**Comment by ChcJohnie** [comment]
Thanks, definitely agree about folder UI from pure email preview feature perspective. Previously got feeling that templates preview should be bit more streamlined (without caring about underneath folder structure) but honestly dont have nice ui in mind and agree my solution is confusing. So in the end better to make it more clear with folders 👍

**Comment by ChcJohnie** [comment]
Slightly middle ground attempt inspired by VsCode explorer uploaded (utilizing chevron icons and folder level border mixed with my  coloring)
wdyt @iamhectorsosa

**Comment by iamhectorsosa** [comment]
There are still some elements from the current design we've removed, can we reinstate the header? the path can be clickable to return to the base dir `src/email`.

image

I am not sure on the chevron, looks like a toggleable list but it doesn't work like one. Once you expand it you cannot collapse it. That's why I would keep it simple and minimal.

Here is an example on how I've seen codeblocks do it. They are using some weird character but with those chars I did the mockup that I shared.

```
├── general
  └── booking-confirmation.tsx
  └── competition.tsx
```

I would say let's keep it simple, but if you want to use some icons I'm all up for it.

**Review by iamhectorsosa — COMMENTED** [review]
There are still some elements from the current design we've removed, can we reinstate the header? the path can be clickable to return to the base dir `src/email`.

image

I am not sure on the chevron, looks like a toggleable list but it doesn't work like one. Once you expand it you cannot collapse it. That's why I would keep it simple and minimal.

Here is an example on how I've seen codeblocks do it. They are using some weird character but with those chars I did the mockup that I shared.

```
├── general
  └── booking-confirmation.tsx
  └── competition.tsx
```

I would say let's keep it simple, but if you want to use some icons I'm all up for it.

**Comment by ChcJohnie** [comment]
Okay, I probably like my proposal more but usually I dont match well with normal user in controversial UI stuff so Im ok to accept defeat 🙂 
I added minimal file tree representation. Should I also remove my "nice labels" and revert to filename (Tips for trips -> tips-for-trips.tsx)?

**Review by iamhectorsosa — COMMENTED** [review]
Looking good! I'm sorry to push back on these changes! Thanks for your patience!

Last nits: We are missing the font weight on the Preview Mode text and also let's either remove the paddings to we have those minimal icons aligned OR we can increase them so they can clearly be at an indented level. I'll leave that brush action to you.

image

**Comment by ChcJohnie** [comment]
Thats okay
Tested with multiple folders, and decided for larger indent

**Review by iamhectorsosa — APPROVED** [review]

**Comment by iamhectorsosa** [comment]
Thanks for this work! Hopefully we can move forward with

- #160 
- #181 

I will take #181 to move a bit faster

**Pull request merged**
