### PR TITLE
Self hosting shiki languages

### LINKED ISSUE #172: Improving Shiki Language performance by Hosting Language
https://github.com/shikijs/shiki/blob/main/docs/languages.md

### PR DESCRIPTION
**Pull request by iamhectorsosa**
Closes #172

### CODE REVIEW

**Comment by iamhectorsosa** [comment]
@ericvalcik it doesn't seem to affect the build times that much. Might not be worth loading the languages locally.

image

**Comment by ericvalcik** [comment]
Yeah, I'm not sure what is causing the build times to be so high. All I know is that it is probably the static site generation, because we had to increase the `staticSiteGenerationTimeout` for the builds to even be successful, so my money is on that.

https://github.com/webscopeio/mailingui/blob/35b6de943a0cbf196ab3f43b5054c1f712fa13f9/next.config.mjs#L25

I thought it was the shiki stuff - maybe we could compare build with that does not run shiki at all (same as in development) and see if there is some improvement?

**Comment by iamhectorsosa** [comment]
@ericvalcik 



image

**Comment by iamhectorsosa** [comment]
Maybe we should consider using another library for this? Any thoughts guys? @ericvalcik @ChcJohnie

**Comment by ChcJohnie** [comment]
No ideas about other options, but might be worth to at least experiment 🙂 
Maybe something might be saved with caching of getHighlighterFromShiki call result  - so its called only once (unless shiki itself has cache already)? but guessing main burden is coming from actual highlight calls

**Comment by ChcJohnie** [comment]
Also in one discussion there was mention about codeToThemedTokens includeExplanation option 

`const tokens = highlighter.codeToThemedTokens(
    code,
    isDevelopment ? "" : lang,
    theme,
    {
      includeExplanation: false,
    }
  );`

Might be worth of try, but cannot find it in docs

**Comment by iamhectorsosa** [comment]
Interesting, can you share the link?Wonder how much would it affect. We can test, although I have no idea of  the implications on this property.

**Comment by ericvalcik** [comment]
I don't know any other options, we'd have to do some research I suppose. I'm surprised that shiki works so badly for us, I worked with it before when using [Nextra](https://nextra.site/)and I never had any notable performance problems with it.

Maybe that is not the best metric, but I always thought that shiki worked fine and was the best option for this so maybe we also could check the integration of the lib, if that could be changed, and if that would improve the performance.

**Comment by ChcJohnie** [comment]
> Interesting, can you share the link?Wonder how much would it affect. We can test, although I have no idea of the implications on this property.

https://github.com/shikijs/shiki/issues/197#issuecomment-922394734

**Comment by iamhectorsosa** [comment]
Seems that this is defaulted to false, @ChcJohnie 

image

**Comment by iamhectorsosa** [comment]
https://rehype-pretty-code.netlify.app/ seems to be using a cache system. We might try to use everything with this plugin otherwise we might have to check other solutions.

Not a priority for now, but definitely something to look into to.

Will probably close this PR with comment. Any last thoughts? @ericvalcik @ChcJohnie

**Pull request closed without merging**
