### PR TITLE
Update email templates and adjust the structure

### LINKED ISSUE #181: Templates Part 3 Create Categories for the Minimal Templates
We want to create categories for the email templates to bring them closer to actual business use cases. Here I've proposed organizing some of them and also creating new templates based on existing ones to fit them better to a certain category.

This issue is NOT for development. It is only for updating/creating/organizing the templates

### Events

Event Invitation
Event Confirmation (renamed from Booking confirmation)
Event Details (renamed from Dinner Reservation)
Event Review (renamed from Review)
Event Suggestions (renamed from Tips for Trips)

### Marketing

Campaign Announcement (renamed from Competition)
Discount Code
News Update (renamed from News)
Product Review (renamed from Review)

### Newsletter
Subscription Confirmation (repurposed from Password Reset)
Subscription Success (repurposed from News)
Company Updates (repurposed from Tips for Trips

### PR DESCRIPTION
**Pull request by ericvalcik**
This PR resolves #181 

Check it out, I feel like there is a lot of stuff and I will double-check everything one more time, but please go through the templates guys to find as many inconsistencies as possible.

Tell me what you think!

### CODE REVIEW

**Review by iamhectorsosa — COMMENTED** [review]
Looks great! This is exactly what we should be shooting for. I would like for someone product-oriented to take a look at these and give us some feedback as well. Perhaps we should merge them and then iterate on them in a separate PR.

With this change merged, Honza can work more on creating the docs links for each of these categories.

@ChcJohnie @ericvalcik

**Comment by ericvalcik** [comment]
I agree. If you guys don't see any big issues with the current designs I think we can definitely merge them.

**Review by ChcJohnie — APPROVED** [review]
Nice, nothing broken spotted and not much into content review (lgtm)

Future consideration - dummy links to mailingui/index instead of google? also footer page links (terms of service etc.) working bit strange inside iframe @iamhectorsosa

**Comment by ericvalcik** [comment]
@iamhectorsosa merge it if you are okay with it

**Pull request merged**
