### PR TITLE
Landing page redesign

### PR DESCRIPTION
**Pull request by ericvalcik**
I did a redesign of the landing page, the designs I created for this change are [here](https://www.figma.com/file/YCzuzebvu1nWuo9T3cCo9q/html.to.design-(Community)?type=design&node-id=0%3A1&mode=design&t=RrNXVBPRIsYGnVQx-1).

Let me know what you guys think, as I'm not very experienced and confident in my design decisions, please feel free to add any comments regarding the design too, thanks!

image

### CODE REVIEW

**Review by iamhectorsosa — COMMENTED** [review]
Looks great but I want to take a look at the code a bit closer. I'm worried to replace the landing and completely dropping the newsletter, the CTA to view templates.

**Comment by ericvalcik** [comment]
Hey @iamhectorsosa, I'm sorry that I'm leaving the PR in this state, but unfortunately, I didn't have enough time to finish it, so not it is up to you.

Some things though I'd like to point out, I played around with the padding of the containers for the examples and also the background color for the padding of the containers; The way you left it, there was a slightly different color in the padding, and tbh after playing with it, the way it is now (with `p-2` and `bg-white` in `<Wrapper>`) I like it the most, but feel free to change it up, my feelings won't be hurt 😁.

**Comment by iamhectorsosa** [comment]
Updated the slots that you gave me for the components and restructured the code a bit. If we want to include more examples we need to wire iframes. Otherwise we are limited to what our current TailwindCSS styles allow us.

**Review by iamhectorsosa — APPROVED** [review]
LET'S GO

**Pull request merged**
