### PR TITLE
/docs/usage page

### LINKED ISSUE #120: Create docs that describe how to set up our library with providers
In the latest PR #113, we added our own version of the `render` utility (a wrapper of react.email's `render` with some added functionality), but we should also create some documentation showing how to render the React components with our `render` utility and how to send the rendered HTML with providers.

Very similar to what react.email does [here](https://react.email/docs/integrations/overview) under Integrations.

### PR DESCRIPTION
**Pull request by ChcJohnie**
closes #120 

Page content should be ready
Open to any content suggestions
Keeping page shorter with two Resend/Nodemailer tabs is deliberate design decision but if you feel this structure is hard to understand, no problem to change into one tabs with all steps OR no tabs with both Using Resend and Using Nodemailer displayed. 
Added another helper Mdx component, tryed to use primitive components but feeled too complicated to get working in MDX. But still feel better level abstraction could be found as there are multiple similar Code helpers (but maybe would required higher verbosity in mdx).

### CODE REVIEW

**Comment by ChcJohnie** [comment]
To review full process, I tried to spin next app which provides send email capability. My test [repo](https://github.com/ChcJohnie/mailingui-test)

I am not sure if I matched intended usage but might be worth of check (current version is api based, i tried experimental server action with similar results, send from client component did not work which might be expected?)

But I encountered bug when email is not rendered with `'use client'` directive inside mailingui component file. Working testing email is with directive edited out from mailingui `Text` component. When you add directive (as is when mailingui is installed/copied) email render throws error. Easier to test with send in console (skips sending part but that one works okay)

**Review by iamhectorsosa — COMMENTED** [review]
Just checking the UX here.

I would make a clear note before starting with the examples that more integrations are available with more email providers and then link the integrations page. This is important for the user to understand that this not only works with these two email providers.

Looks good. Nice touch with creating tabs for examples with resend and nodemailer.

Nice idea with the useful links section. These links should be bullet lists.

**Comment by ChcJohnie** [comment]
Update steps to be more real-world. 
Using guide will most likely render error until #205 is fixed

**Review by iamhectorsosa — APPROVED** [review]
Looking great!

**Pull request merged**
