### PR TITLE
Updating Documentation

### LINKED ISSUE #178: Add Tabs for Automatic and Manual Installation on Individual Components
Similar to how we have the general Installation instructions, let's add these tabs to the individual components

### LINKED ISSUE #179: Update the Component Description to sync with Landing page
The landing page has very nice component descriptions. These should be updated on each component page.

### PR DESCRIPTION
**Pull request by iamhectorsosa**
Closes #178 and Closes #179

### CODE REVIEW

**Comment by iamhectorsosa** [comment]
Please don't forget to review this one.

CC @ChcJohnie @ericvalcik

**Comment by ericvalcik** [comment]
Looking good, nice work! I'm also sorry for the late review.

Maybe one little question, for the manual install tab - wouldn't a little note above the code block saying something like "Copy this file inside the folder with your components" be nice to have there? Right now it just shows the file and that could be a little confusing. what do you guys think?

**Comment by iamhectorsosa** [comment]
> _Looking good, nice work! I'm also sorry for the late review. Maybe one little question, for the manual install tab - wouldn't a little note above the code block saying something like "Copy this file inside the folder with your components" be nice to have there? Right now it just shows the file and that could be a little confusing. what do you guys think?_

@ericvalcik good suggestion. I've added the following on top of each snippet.

> _Choose an a) automatic Install by running our `@mailingui/cli` following the commands/options provided or b) install manually by copying and pasting directly into your `src/mailingui/components` directory._

**Review by ericvalcik — APPROVED** [review]

**Comment by ChcJohnie** [comment]
Looks fine 
Not sure where to place it, but minor, slightly off topic observations:

- quote 'into your src/mailingui/components' , maybe bit more general placement description could be found (as we are not requiring exact structure
-  noticed that in tsconfig.json step we suggest adding alias to components/index.ts, but think there is no word about having barrel components file in user repo throughout docs (is cli adding this?)
- feature suggestion - could we have /docs/cli with all CLI methods and options listed. So in automatic installation section we can have only default cli command for that install without options clutter etc. (looks bit confusing to me)

**Review by ChcJohnie — APPROVED** [review]

**Comment by iamhectorsosa** [comment]
Good suggestions, @ChcJohnie . Let's log issues for them. Here are my comments on them:
1. We are suggesting this structure as recommended to use our path aliases (installation docs overview). Of course, they users can choose not follow it. We could word this a bit better in the installation docs but would have to unify our suggestion here. Can open an issue and suggest a draft in what works best.
2. Adding all of the methods and options is a great suggestion. Although, I would keep the description of the options in the components automatic install section just for clarity. I don't feel like three or 5 additional lines are clutter.

**Pull request merged**
